### ISSUE TITLE
[FEATURE]: simplest deployment

### ISSUE THREAD

**Issue by shanduur-auto** [registry-operator/registry-operator#1]
### Is your feature request related to a problem? Please describe.

Deploying minimal registry for development or evaluation purposes should be as simple as possible.

### Describe the solution you'd like.

Creating the following resources should result in creating set of base Kubernetes resources:

- Input:
    ```yaml
    apiVersion: registry-operator.dev/v1alpha1
    kind: Registry
    metadata:
      name: simplest-registry
      namespace: default
    ```
- Result
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: simplest-registry
      namespace: default
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: simplest-registry
        app.kubernetes.io/managed-by: registry-operator
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: registry
          app.kubernetes.io/instance: simplest-registry
      template:
        metadata:
          labels:
            app.kubernetes.io/name: registry
            app.kubernetes.io/instance: simplest-registry
        spec:
          containers:
          - name: registry
            image: docker.io/library/registry:2
            ports:
            - containerPort: 5000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: simplest-registry
      namespace: default
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: simplest-registry
        app.kubernetes.io/managed-by: registry-operator
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: simplest-registry
      ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
    ```

### Describe alternatives you've considered.

N/A
