### ISSUE TITLE
[FEATURE]: add resources requests/limits

### ISSUE THREAD

**Issue by shanduur** [registry-operator/registry-operator#61]
### Is your feature request related to a problem? Please describe.

Currently, the Registry CRD does not allow users to specify resource requests and limits for the underlying container. This can lead to resource contention or inefficiencies in cluster utilization, especially in environments with strict resource quotas.

### Describe the solution you'd like.

Support for specifying resource requests and limits in the Registry CRD. The following example demonstrates the desired functionality:

```yaml
---
apiVersion: registry-operator.dev/v1alpha1
kind: Registry
metadata:
  name: my-registry
spec:
  image: registry:2 
  resources:
    requests:
      cpu: "500m"      # CPU resource requests
      memory: "1Gi"    # Memory resource requests
    limits:
      cpu: "1"         # CPU resource limits
      memory: "2Gi"    # Memory resource limits
```

When applied, these values should be propagated to the corresponding Kubernetes Deployment, ensuring the resource constraints are enforced for the registry container.

### Describe alternatives you've considered.

1. Manually editing the Deployment created by the operator to add resource constraints. However, this is error-prone and doesn't align with declarative infrastructure practices.
1. Not specifying resource constraints and relying on Kubernetes defaults, which can lead to resource contention or unintentional over-provisioning in shared clusters.
